{"uuid": "5c509063-99a3-499d-805a-c12100df92ea", "children": ["d18c723d-d61f-4eff-b6aa-218ac8020755"], "befores": [{"name": "driver_ecshop", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0056DCE3+50899]\n\t(No symbol) [0x004FE111]\n\t(No symbol) [0x00405588]\n\t(No symbol) [0x00420AAB]\n\t(No symbol) [0x0041F479]\n\t(No symbol) [0x00451FFE]\n\t(No symbol) [0x00451CEC]\n\t(No symbol) [0x0044B6F6]\n\t(No symbol) [0x00427708]\n\t(No symbol) [0x0042886D]\n\tGetHandleVerifier [0x007D3EAE+2566302]\n\tGetHandleVerifier [0x008092B1+2784417]\n\tGetHandleVerifier [0x0080327C+2759788]\n\tGetHandleVerifier [0x00605740+672048]\n\t(No symbol) [0x00508872]\n\t(No symbol) [0x005041C8]\n\t(No symbol) [0x005042AB]\n\t(No symbol) [0x004F71B7]\n\tBaseThreadInitThunk [0x767A0099+25]\n\tRtlGetAppContainerNamedObjectPath [0x772D7B6E+286]\n\tRtlGetAppContainerNamedObjectPath [0x772D7B3E+238]\n\n", "trace": "  File \"d:\\python3.10.0\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python3.10.0\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python3.10.0\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\py\\testcase\\conftest.py\", line 40, in driver_ecshop\n    driver=webdriver.Chrome(r'D:\\python3.10.0\\Scripts\\chromedriver.exe')\n  File \"d:\\python3.10.0\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 80, in __init__\n    super().__init__(\n  File \"d:\\python3.10.0\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"d:\\python3.10.0\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\python3.10.0\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\python3.10.0\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python3.10.0\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1683882830801, "stop": 1683882833348}], "start": 1683882830801, "stop": 1683882833387}